### ISSUE TITLE
Add type hints in Python code

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-python-client#75]
# Description

Type hints specify the expected types of function arguments, return values, and variables in Python code. Adding type hints improves code readability, making it easier for team members to understand the intended use of functions and variables.

This results in more maintainable code and speeds up development by catching potential issues before runtime.

# Task

- [x] Add type hints in [cytomine.py](https://github.com/Cytomine-ULiege/Cytomine-python-client/blob/main/cytomine/cytomine.py)
- [x] Add type hints in [utilities/annotations.py](https://github.com/Cytomine-ULiege/Cytomine-python-client/blob/main/cytomine/utilities/annotations.py)
- [x] Add type hints in [models/annotation.py](https://github.com/Cytomine-ULiege/Cytomine-python-client/blob/main/cytomine/models/annotation.py)
- [x] Add type hints in [models/collection.py](https://github.com/Cytomine-ULiege/Cytomine-python-client/blob/main/cytomine/models/collection.py)
- [x] Add type hints in [models/image.py](https://github.com/Cytomine-ULiege/Cytomine-python-client/blob/main/cytomine/models/image.py)
- [x] Add type hints in [models/imagegroup.py](https://github.com/Cytomine-ULiege/Cytomine-python-client/blob/main/cytomine/models/imagegroup.py) 
- [x] Add type hints in [models/model.py](https://github.com/Cytomine-ULiege/Cytomine-python-client/blob/main/cytomine/models/model.py)
- [x] Add type hints in [models/_utilities](https://github.com/Cytomine-ULiege/Cytomine-python-client/tree/main/cytomine/models/_utilities) 
- [x] Add type hints in [models/ontology.py](https://github.com/Cytomine-ULiege/Cytomine-python-client/blob/main/cytomine/models/ontology.py)
- [x] Add type hints in [models/project.py](https://github.com/Cytomine-ULiege/Cytomine-python-client/blob/main/cytomine/models/project.py)
- [x] Add type hints in [models/property.py](https://github.com/Cytomine-ULiege/Cytomine-python-client/blob/main/cytomine/models/property.py)
- [x] Add type hints in [models/social.py](https://github.com/Cytomine-ULiege/Cytomine-python-client/blob/main/cytomine/models/social.py)
- [x] Add type hints in [models/storage.py](https://github.com/Cytomine-ULiege/Cytomine-python-client/blob/main/cytomine/models/storage.py)
- [x] Add type hints in [models/track.py](https://github.com/Cytomine-ULiege/Cytomine-python-client/tree/main/cytomine/models/track.py)
- [x] Add type hints in [models/user.py](https://github.com/Cytomine-ULiege/Cytomine-python-client/tree/main/cytomine/models/user.py)
